name: 🐶 Dogtor-App
on:
  push:
    branches:
      - main

jobs:
  update:
    name: EAS Update
    runs-on: ubuntu-latest
    steps:
      - name: Check for Env Vards 
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets."
            exit 1
          fi
          if [ -z "${{ secrets.SHOULD_USE_AI }}" ]; then
            echo "You must provide an SHOULD_USE_AI secret linked to this project's Expo account in this repo's secrets."
            exit 1
          fi
          if [ -z "${{ secrets.OPEN_AI_API_KEY }}" ]; then
            echo "You must provide an OPEN_AI_API_KEY secret linked to this project's Expo account in this repo's secrets."
            exit 1
          fi


      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: yarn

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: yarn install

      - name: Publish update
        run: SHOULD_USE_AI=${{ secrets.SHOULD_USE_AI }} OPEN_AI_API_KEY=${{ secrets.OPEN_AI_API_KEY }} eas update --auto
